Create Slack-Notification.yaml
indeni/cloudrail-vscode-extension pull request #41
Opened 2021-12-30 13:17 UTC by dereban25

If failed CI/CD send message to personal slack channel

2022-01-02 09:19 UTC, alonashkenazi commented
We need to also notify to cloudrail-dev channel when we release a new version (only from main)

2022-01-02 09:19 UTC, alonashkenazi requested changes

2022-01-02 09:19 UTC, alonashkenazi commented on .github/workflows/Slack-Notification.yaml
> +name: Slack-Notification
rename file to slack-notification.yaml (all lower case)

2022-01-04 06:46 UTC, dereban25 commented on .github/workflows/Slack-Notification.yaml
> +name: Slack-Notification
Done.I changed a name of file and added trigger on release.

2022-01-04 09:01 UTC, closed without merging

2022-01-04 09:01 UTC, dereban25 commented
Added another pull request